# Generated by Django 4.1.5 on 2023-01-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
